### ISSUE TITLE
quick_explore does not save images if we enter plotfile as argument

### ISSUE THREAD

**Issue by BelhalK** [probcomp/bdbcontrib#113]
ed.quick_explore_cols(cols, plotfile='output') should save my three figures (pariplots, heatmap of cols and n number of heatmaps (according to the n number of variable in cols) in a file named output.png.
![capture d ecran 2016-02-19 a 15 18 37](https://cloud.githubusercontent.com/assets/15817944/13187880/147b9528-d71c-11e5-85ca-b16fa00f0ca2.png)

Nothing is being saved while running this query.

Also, as I would like to have the three figures saved in separate png files, is 'plotfile' supposed to save those three files in three different pngs?

**Comment by gregory-marton** [comment]
The default logger's behavior is to try to plt.show(). My bad for not remembering that. Try instead:

    from bayeslite.loggers import LoggingLogger
    ... quickstart(..., logger=LoggingLogger())

Another choice is to use CaptureLogger:

    from bayeslite.loggers import CaptureLogger
    capture_logger = CaptureLogger()
    ... quickstart(..., logger=capture_logger)
    [do some plotting]
    plots = dict([(name, mpl_figure) for (command, name, mpl_figure) in capture_logger.calls 
                  if command == "plot" ])

or something along those lines (I didn't try evaluating that code, so it probably has bugs, but I hope you get the idea.)
Examine the relevant code for more details:
https://github.com/probcomp/bayeslite/blob/master/src/loggers.py
