### ISSUE TITLE
Float division by zero

### ISSUE THREAD

**Issue by BelhalK** [probcomp/bdbcontrib#120]
q('''
ESTIMATE SIMILARITY WITH RESPECT TO "Enrollment of undergraduate degree-seeking students" FROM PAIRWISE %g
''')
returns
Message error : "Float division by zero"

Even when I'm filling all the missing values by 0 or the mean of the related column
It should not be an issue I believe and it was working weeks ago..

![capture d ecran 2016-03-24 a 12 24 01](https://cloud.githubusercontent.com/assets/15817944/14023582/596c1aa4-f1bb-11e5-820d-db714945dd80.png)

**Comment by riastradh-probcomp** [comment]
Do you have any models?

**Comment by BelhalK** [comment]
Fixed by initializing models
Issued closed cf #386 in probcomp/bayeslite
