### ISSUE TITLE
Unable to plot heatmap

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/bdbcontrib#123]
Following legacy code, one could plot a heatmap through bdbcontrib.heatmap(), which doesn't exist anymore. I know of plot_utils.heatmap, but the arguments are different from the bdbcontrib version and the documentation is not clear to me. Reading the tests also did not provide a practical user case, as the test functions has complex dependencies.

**Comment by gregory-marton** [comment]
Do you have a list of ways you tried? Did you try using your_population.heatmap?
Do you have a sense of what in the documentation was confusing? 
How did you view the documentation: in the source, or using the help() facility, or in the generated pdf?

**Comment by leocasarsa** [comment]
My current code, following the satellites.ipynb in bayesdb-demo (and the parallelization options that we've discussed)
```
name = "casarsa"
email = "casarsa@mit.edu"
with open('bayesdb-session-capture-opt.txt', 'w') as optfile:
    optfile.write('%s <%s>\n' % (name, email))
bdb = bayeslite.bayesdb_open('pilot.bdb', builtin_metamodels=False)
crosscat = ccme.MultiprocessingEngine(seed=1)
metamodel = CrosscatMetamodel(crosscat)
bayeslite.bayesdb_register_metamodel(bdb, metamodel)
pilot = quickstart(name='pilot_cc', bdb_path='pilot.bdb')
q = pilot.q
pilot.heatmap('''ESTIMATE CORRELATIONS FROM PAIWISE COLUMNS OF pilot_cc;''')
plt.save_fig('correlations.pdf')
plt.show()
```
Error in quickstart:
```
  File "heatmaps_bql.py", line 29, in <module>
    pilot = quickstart(name='pilot_cc', bdb_path='pilot.bdb')
  File "build/bdist.linux-x86_64/egg/bdbcontrib/__init__.py", line 30, in quickstart
    
  File "build/bdist.linux-x86_64/egg/bdbcontrib/population.py", line 119, in __init__
  File "build/bdist.linux-x86_64/egg/bdbcontrib/population.py", line 164, in initialize
bayeslite.exception.BayesLiteException: No data sources specified, and an empty bdb.
```
Although pilot.bdb has 24 M of size.

**Comment by leocasarsa** [comment]
Old-style code that Feras indicated:

```
bdbcontrib.heatmap(
        bdb, '''ESTIMATE CORRELATION FROM PAIRWISE COLUMNS OF pilot_cc;''')
plt.save_fig('correlations.pdf')
plt.show()
```
Works in previous versions of bdbcontrib, but in the latest, sends the error:
```
  File "heatmaps_bdbcontrib.py", line 23, in <module>
    bdbcontrib.heatmap(
AttributeError: 'module' object has no attribute 'heatmap'
```

**Comment by gregory-marton** [comment]
I think the first approach may be a case of a bad error message. Try
`quickstart(name='pilot', bdb_path='pilot.bdb')`
Note the lack of '_cc' in the name. That refers to the crosscat generator, not to the data table.

For the second approach (which I recommend against for end-user code like this), you need bdbcontrib.plot_utils.heatmap now, and you need to pass it a dataframe, so 
```
bdbcontrib.plot_utils.heatmap(bdb, bdbcontrib.bql_utils.query('''ESTIMATE CORRELATION...'''))
```

**Comment by gregory-marton** [comment]
For the first approach, there may also be an issue with opening the same bdb twice. You do instead:
```
with bayesdb_open(pathname='pilot.bdb', builtin_metamodels=False) as bdb:
    crosscat = ccme.MultiprocessingEngine(seed=1)
    metamodel = CrosscatMetamodel(crosscat)
    bayeslite.bayesdb_register_metamodel(bdb, metamodel)
```
The bdb then closes itself at the end of the with, and you should have no trouble when opening it again with quickstart.

**Comment by leocasarsa** [comment]
Thanks, Grem, I'm going to try them out soon enough. Right now I've downgraded bdbcontrib to match Feras' version due to lack of time. I'll close the issue after trying your suggestions.
