### ISSUE TITLE
Rename column in table and generator of my bdb file

### ISSUE THREAD

**Issue by BelhalK** [probcomp/bdbcontrib#125]
I would like to manually change one column name of my bdb file
(Why manually? 
Because after having done it automatically for all the other columns and run 3 hours of analysis, I would rather just change this single variable and keep my analysis)

I tried ALTER but does not seem to work
cf photo: First column ABCIRCM that I'm trying to change into test_name
![capture d ecran 2016-05-03 a 18 41 56](https://cloud.githubusercontent.com/assets/15817944/15000565/bf31daaa-115e-11e6-87e5-d8679501e6ac.png)

**Comment by riastradh-probcomp** [comment]
https://github.com/probcomp/bayeslite/issues/35

**Comment by BelhalK** [comment]
Thanks
