### ISSUE TITLE
satellites/querying-and-plotting.ipynb not included in last bdbcontrib update

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/bdbcontrib#144]
![image](https://cloud.githubusercontent.com/assets/11274668/15306003/f10d3bce-1b94-11e6-8d41-b7d143a5c073.png)

**Comment by leocasarsa** [comment]
![image](https://cloud.githubusercontent.com/assets/11274668/15306013/10349a24-1b95-11e6-9216-104aa9c68c0e.png)

**Comment by gregory-marton** [comment]
Fixed at head, and distributed to pypi, etc. Great catch!
