### ISSUE TITLE
Why is "name" a necessary argument of Population?

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/bdbcontrib#145]
If the bdb file already exists, it already has one and only one population table associated with it. Asking for the user to input a name is only sensible when the bdb file does not exist already.

**Comment by gregory-marton** [comment]
A bdb may have multiple populations stored in it. Right now none of that is explicit so we don't even have a place to start. Once it's explicit, we might reasonably have a default, but requiring a name doesn't seem onerous. We should have good messages in case there is an apparent conflict or duplication. In person you seemed to like where we were headed on that score with the recently updated message that does list_tables and list_generators on the bdb for you, so I'm closing this for now. We'll improve on that when we can.
