### ISSUE TITLE
Checked-in MA schools example ipynb is messy

### ISSUE THREAD

**Issue by fsaad** [probcomp/bdbcontrib#150]
A user reading the notbeook should not be seeing hundreds of lines of 

> Cannot convert [$24,027,141]/<type 'unicode'> because [could not convert string to float: $24027141]

and the like.

**Comment by gregory-marton** [comment]
The fact readers may not like that mess is an intended feature (incentivizing them to clean it up, as expected by the adjacent exercise) rather than a failure of planning. I'm open to the idea that the exercise should be changed, but I think this mess serves the exercise well.

**Comment by fsaad** [comment]
In that case, should migrate this from "examples" in bdbcontrib to "excercises" in the iap 2016 repository. These examples directory are instances of bayeslite analyses on datasets, and looking over this notebook as a cursory glance gives an impression that the system is messed up because the notebook presentation is bad.

**Comment by gregory-marton** [comment]
Rather, I think we should migrate iap2016 materials here, and indeed rename the directory "examples" --> "tutorial".

**Comment by fsaad** [comment]
OK, in that case I will create a separate ticket outlining that we need to agree how exactly we intend on presenting ipython notebooks for public consumption.
