### ISSUE TITLE
Importing bdbcontrib takes a while

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bdbcontrib#30]
From @luac:
> importing bdbcontrib takes a while?

**Comment by gregory-marton** [comment]
Today, on my laptop:

```
    real	0m0.653s
    user	0m0.435s
    sys  	0m0.114s
```

**Comment by riastradh-probcomp** [comment]
For the record, the change that had this effect was fe43736da8aa6051df9c01e631fbdeee321bf5b0.
