### ISSUE TITLE
seaborn div0s on plotting super-skewed distributions.

### ISSUE THREAD

**Issue by gregory-marton** [probcomp/bdbcontrib#40]
https://github.com/mwaskom/seaborn/blob/master/seaborn/distributions.py line 27 has
    h = 2 * iqr(a) / (len(a) ** (1 / 3))
And iqr (inter-quartile range) can be zero for skewed distributions that are otherwise plottable.
It should fall back to max(a) - min(a) but doesn't.
I don't think I can fix that from outside.

**Comment by axch** [comment]
Resolved, I believe, by 04b9939b049e97b43aed259e761952f9a04eb910 and then by upgrading to Seaborn 0.6
