### ISSUE TITLE
osx app: no module named ipykernel

### ISSUE THREAD

**Issue by marcoct** [probcomp/bdbcontrib#60]
[I 11:25:06.744 NotebookApp] Kernel started: b9215e58-990d-4371-8aaf-d763eb5e639f
/Applications/Bayeslite-bayes0.1+unknown.app/Contents/MacOS/venv/bin/python2.7: No module named ipykernel

However, my sys.path when run within the venv does not include anything from the app, so this might be an issue with my system configuration of virtualenv?

**Comment by gregory-marton** [comment]
Did you have a ~/.ipython, and if so, did moving it out of the way help?

**Comment by marcoct** [comment]
I did, but moving it out of the way did not help.

**Comment by gregory-marton** [comment]
@riastradh-probcomp , this might be worth your time to look into. I'm out of ideas on what could be causing it, and therefore have no idea how to test for it in the osx-dmg suite.

**Comment by riastradh-probcomp** [comment]
@marcoct, how exactly are you observing the symptom about sys.path?

Can anyone else reproduce this?

**Comment by raxraxraxraxrax** [comment]
This looks to be the same issue as https://github.com/probcomp/bayeslite/issues/138 and assuming that's true: @gregory-marton , you said you were going to try to sneak a fix for this in this week; is that still likely?

**Comment by gregory-marton** [comment]
I think I did fix this. Please reopen if it's still an issue.
