### ISSUE TITLE
operator_owner is independent of country_of_operator?

### ISSUE THREAD

**Issue by axch** [probcomp/bdbcontrib#61]
In the actual data, the relationship is nearly deterministic in one direction:
```
select operator_owner, count(distinct country_of_operator) as ct
from satellites
group by operator_owner
order by ct desc
limit 1
```
says "Ministry of Defense, 3", but crosscat almost uniformly decides not to cluster them.  @vkmvkmvkmvkm says this is likely due to operator_owner being a large (346 items) categorical, thus messing everything up.

**Comment by gregory-marton** [comment]
See also #63

**Comment by gregory-marton** [comment]
I've answered this in more detail on #63, and will close this as a duplicate.
