### ISSUE TITLE
Consider adding a "drop table if exists X" example to the notebook

### ISSUE THREAD

**Issue by marcoct** [probcomp/bdbcontrib#62]
This may reflect my own relative lack of experience with databases relative to the expected user base, but including an example of e.g.:
```
q('drop table if exists satellite_purpose')
```
prior to creating a new table might save certain users some time in figuring out how to use the tool.

**Comment by fsaad** [comment]
What is the expected behavior of this query?

**Comment by marcoct** [comment]
If the user is modifying the notebook, and re-running cells, the "table already exists error" is bound to arise, and adding this line above the "create temp table..." line may streamline the debugging process for db-naive users. This "drop table..." query deletes the table, and does nothing if the table does not already exist, allowing the block to be run repeatedly.

**Comment by fsaad** [comment]
Oh I see -- the best way to currently do this is:
```
if bayeslite.core.bayesdb_has_table(bdb, tab):
    q('DROP TABLE tab')
```

**Comment by marcoct** [comment]
As an alternative, perhaps there is a way to augment the "create temp table" command to have it delete the table if it exists before reating it.

**Comment by marcoct** [comment]
Just to be clear, this does work:
```
q('drop table if exists satellite_purpose')
```
I'm just suggesting adding it to the checked-in notebook cells.

**Comment by raxraxraxraxrax** [comment]
This would have made my working with satellites so much easier.

**Comment by gregory-marton** [comment]
b70a832
