### ISSUE TITLE
Session capture UI nits

### ISSUE THREAD

**Issue by axch** [probcomp/bdbcontrib#66]
- A big, bold WARNING feels overkill for a non-session-breaking error,
  especially since the query that printed it was the one in which I
  fixed it.
- Not telling me the object whose send_session_data method to call is
  somewhat underhelpful, but I don't know a good way to fix that

**Comment by gregory-marton** [comment]
Having implemented higher level session capture in BqlRecipes, I think both of these are resolved. We will not routinely be capturing sessions using a SessionOrchestrator, and instead are sending individual session elements (commands and their data) immediately as they are issued, so there is no need for a warning. If we were to start using a session orchestrator, the right way to do that would not be to put one into the notebook, but to add one to the BqlRecipes object, at which point the object on which to call that method would be obvious.
