### ISSUE TITLE
ERROR at teardown of test_similar_rows

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bdbcontrib#92]
____________________ ERROR at teardown of test_similar_rows ____________________

    _module = <module 'test_recipes' from '/home/riastradh/bayesdb/bdbcontrib/dist/bdbcontrib-0.1.3rc2/tests/test_recipes.py'>

	def teardown_module(_module):
	    with prepare() as (dts, _df):
    >           os.remove(os.path.dirname(dts.csv_path))
    E           AttributeError: 'BqlRecipes' object has no attribute 'csv_path'

**Comment by gregory-marton** [comment]
Underlying issue is that it should be called .csv_path everywhere and is actually called .csv almost everywhere. Will fix that.

Why didn't jenkins detect this?

**Comment by riastradh-probcomp** [comment]
The fix is easy.  Why it passed in jenkins is totally beyond me.

**Comment by riastradh-probcomp** [comment]
pytest 2.5.1 -- as jenkins is using -- does not seem to run setup_module/teardown_module, so instead we're accruing dozens of megabytes of empty temporary directories in /tmp.  pytest 2.8.1 -- as pip installed for me -- does seem to run them.

**Comment by riastradh-probcomp** [comment]
On further analysis, I don't actually see differences between pytest 2.5.1 and pytest 2.8.1 here.  On a trivial file of tests I created to test this, pytest 2.5.1 runs setup_module and teardown_module.  I still have no idea why jenkins isn't finding this.

**Comment by riastradh-probcomp** [comment]
When I run the test from the Git repository with exactly the same versions of python and pytest on my Ubuntu 14.04 system as are installed for jenkins on Ubuntu 14.04, I still hit this error.

**Comment by riastradh-probcomp** [comment]
So jenkins does run setup_module/teardown_module.  It just doesn't report exceptions during teardown.  (Exceptions during setup are not reported, but suppress calling teardown, apparently.)

On my system with the same versions of Ubuntu, Python, and pytest, exceptions during setup and teardown are reported noisily.

This happens for a trivial file of tests run directly with `py.test` or with `env -i /usr/bin/python -m pytest` outside any bayeslite-related directory.  No clue what the difference is.

**Comment by riastradh-probcomp** [comment]
My inclination is to conclude that setup_module/teardown_module is unreliable and to avoid it.

**Comment by gregory-marton** [comment]
Do you have a suggestion as to what to replace it with?



Gregory A. Marton  617-858-0775
http://goo.gl/Ne09o
http://csail.mit.edu/~gremio

**Comment by riastradh-probcomp** [comment]
Easy approach: just make prepare clean up after itself instead of deferring it to the end.

But maybe there's some state you intend to keep between the tests -- which makes it trickier to run tests independently anyway, so I'm inclined to avoid that in the first place, or just merge them all into a single test if you can't run them independently anyway.

**Comment by gregory-marton** [comment]
Disagree. The accumulation in /tmp is not as bad as either merging tests,
thus losing readability and independence, nor as bad as spending the time
to re-analyze the dataset for each test. This is on the order of megabytes
after a fair amount of time, on a filesystem that the system can clean up
if it needs space. I'd rather leave it unreliable.


Gregory A. Marton  617-858-0775
http://goo.gl/Ne09o
http://csail.mit.edu/~gremio

**Comment by riastradh-probcomp** [comment]
There's another bug here -- `os.remove` does not remove directories.

**Comment by gregory-marton** [comment]
Ah! Interesting. Might that explain more of the bad behavior? I'll
certainly fix that...


Gregory A. Marton  617-858-0775
http://goo.gl/Ne09o
http://csail.mit.edu/~gremio

**Comment by gregory-marton** [comment]
shutil.rmtree seems to be a better way.

**Comment by riastradh-probcomp** [comment]
To reduce the effort for clean-up, it would be worthwhile to specify `prefix='bdbcontrib-test'` or something to `tempfile.mkdtemp`.  Otherwise we end up with /tmp/tmpXYZPQR123 which are hard to tell apart.

**Comment by gregory-marton** [comment]
Good call. Added to my change in progress.



Gregory A. Marton  617-858-0775
http://goo.gl/Ne09o
http://csail.mit.edu/~gremio

**Comment by riastradh-probcomp** [comment]
How do you know what order the tests run in?  If you can't rely on it, then interdependent tests are simply wrong; if you can rely on it, we could add a 'test' that runs after all the others and just does the clean-up.

**Comment by gregory-marton** [comment]
Prepare is guaranteed to run before any test that needs it (because they
call it). None of the tests modify the analysis, so their order doesn't
matter.


Gregory A. Marton  617-858-0775
http://goo.gl/Ne09o
http://csail.mit.edu/~gremio

**Comment by riastradh-probcomp** [comment]
Does the link to the file on disk need to continue to exist after prepare returns?  Can we just delete the directory in prepare?

**Comment by gregory-marton** [comment]
The tests analyze once, then use that analysis for all tests, read-only,
thus order-independent. To avoid re-analysis, that state sticks around
between tests, and is only actually created on the first prepare call.


Gregory A. Marton  617-858-0775
http://goo.gl/Ne09o
http://csail.mit.edu/~gremio

**Comment by riastradh-probcomp** [comment]
Yes, I got that.  What I am wondering is whether the directory and links to the bdb file on disk need to continue to exist after the initial call to prepare, once we have a bdb handle.

For that matter, do we even need to have a bdb file on disk?  Can we use an in-memory one?

**Comment by riastradh-probcomp** [comment]
Another thing we could do is:

    # Make sure pytest reports errors in this operation.
    def test_teardown():
        with prepare() as ...:
            shutil.rmtree(whatever)
        testvars['dataset'] = None

    def teardown_module():
        test_teardown()

That does the analysis twice, which is not as good as once, but not as bad as n times for n tests.

**Comment by gregory-marton** [comment]
This was fixed by aab835ed
